### ISSUE TITLE
Compatible with Magento 2.3.1?

### ISSUE THREAD

**Issue by gfxguru** [argento/theme-custom-boilerplates#1]
received quite a few errors "Unable to resolve source file for *.less" trying to deploy content. Is this compatible with Magento 2.3.1?

**Comment by vovayatsyuk** [comment]
Yes, it is. 

This repo is a set of empty themes that are inherited from Argento themes. They don't contain any `less` files.

I recommend you to check permissions in `pub/static/frontend` and `var/view_preprocessed` folders. 

If it won't help, try to deploy using the following command:

```bash
bin/magento setup:static-content:deploy en_US --theme=Local/argento-essence-custom --jobs=1
```
